version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
  books_api:
    image: books:v2
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb
  frontend:
    image: booksfrontend:v2
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - books_api

